### ISSUE TITLE
Error Establishing a Database Connection

### ISSUE THREAD

**Issue by jylenhof** [ACloudGuru-Resources/Course_GKE_Beginner_To_Pro#1]
Hi,

Sent you a message on your Linkedin account yesterday.
Was doing "Demo: Volumes and Persistent Storage" of the "Course_GKE_Beginner_To_Pro" lesson on LinuxAcademy and had some problems starting wordpress. I had the message "Error Establishing a Database Connection" on the run.

**Comment by jylenhof** [comment]
Was able to fix this problem with following fixes :

jygcp_superadmin@cloudshell:~/mysql-demo (projectlinuxacademy-303708)$ diff -uNr mysql-deployment.yaml.NOTOK mysql-deployment.yaml
--- mysql-deployment.yaml.NOTOK 2021-03-24 19:00:45.321495561 +0000
+++ mysql-deployment.yaml       2021-03-25 09:19:03.022523355 +0000
@@ -18,6 +18,8 @@
         - image: mysql:5.6
           name: mysql
           env:
+            - name: MYSQL_DATABASE
+              value: wordpress
             - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
jygcp_superadmin@cloudshell:~/mysql-demo

and

jygcp_superadmin@cloudshell:~/mysql-demo (projectlinuxacademy-303708)$ diff -uNr wordpress-deployment.yaml.NOTOK wordpress-deployment.yaml
--- wordpress-deployment.yaml.NOTOK     2021-03-24 19:01:04.766491721 +0000
+++ wordpress-deployment.yaml   2021-03-25 09:22:32.266348246 +0000
@@ -20,6 +20,10 @@
           env:
           - name: WORDPRESS_DB_HOST
             value: mysql:3306
+          - name: WORDPRESS_DB_NAME
+            value: wordpress
+          - name: WORDPRESS_DB_USER
+            value: root
           - name: WORDPRESS_DB_PASSWORD
             valueFrom:
               secretKeyRef:
jygcp_superadmin@cloudshell:~/mysql-demo (projectlinuxacademy-303708)$

**Comment by rawteech** [comment]
Hi guys am also following this course. I still get this error even when I applied the fix.. not sure if am missing something else
